# kubectl apply -f ./echo-server.yaml
# kubectl port-forward -n playground service/echo-server-service 8080:8080
# kubectl port-forward -n argocd service/argocd-server 8081:443
# login: admin
# password: argocd-initial-admin-secret config

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: playground
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          image: "whsv26/echo-server:1.1.0"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: playground
  name: echo-server-service
spec:
  type: ClusterIP
  selector:
    app: echo-server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP